name: AWESOMO-API CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    container:
      image: node
    steps:
      - uses: actions/checkout@v1
      - name: Install
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: Lint
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: lint
      - name: Test
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test
      - name: Typescript build
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build
  cd:
    name: Deploy to Docker
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Typescript build
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build
      - name: Docker build
        run: docker build -t awesomo-api .
      - name: Docker tags
        run: |
          docker tag awesomo-api ${{ secrets.DOCKER_USER }}/awesomo-api:${{ github.sha }}
          docker tag awesomo-api ${{ secrets.DOCKER_USER }}/awesomo-api:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/awesomo-api:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/awesomo-api:latest
